# Generated by Django 5.0.6 on 2024-06-16 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcriber', '0002_mediafile_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediafile',
            old_name='transcription',
            new_name='vtt_transcription',
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='vtt_file',
        ),
    ]
