# Generated by Django 5.0.6 on 2024-06-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriber', '0003_rename_transcription_mediafile_vtt_transcription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='json_save',
            field=models.TextField(blank=True, null=True),
        ),
    ]
